# Generated by Django 2.2.3 on 2019-12-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0002_user_is_email_verified")]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["last_name", "first_name"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        )
    ]
