# Generated by Django 2.2.3 on 2019-12-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0003_auto_20191216_1156")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        )
    ]
