# Generated by Django 2.2.3 on 2019-12-17 16:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0004_auto_20191216_1424")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="comments",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="picture_file_path",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="picture_file_type",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
