# Generated by Django 2.2.3 on 2019-12-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0005_auto_20191217_1651")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
