# Generated by Django 2.2.3 on 2019-12-18 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_auto_20191218_1028"),
        ("users", "0006_auto_20191217_1723"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked",
            field=models.ManyToManyField(
                blank=True, related_name="_user_blocked_+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                related_name="_user_followers_+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                blank=True, related_name="_user_follows_+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="liked",
            field=models.ManyToManyField(
                blank=True, related_name="liked", to="blog.BlogPost"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog.BlogPost"
            ),
        ),
    ]
