# Generated by Django 2.2.3 on 2019-12-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0007_auto_20191218_1028")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        )
    ]
