# Generated by Django 2.2.3 on 2019-12-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0008_user_date_of_birth")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="picture",
            field=models.ImageField(
                blank=True, upload_to=models.CharField(max_length=128, null=True)
            ),
        )
    ]
