# Generated by Django 2.2 on 2020-01-02 08:50

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=155)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "hashtags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(blank=True),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["title"]},
        )
    ]
