# Generated by Django 2.2.3 on 2019-12-18 10:28

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0002_auto_20191217_1824"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="liked_by",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
