# Generated by Django 2.2 on 2020-01-03 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [("blog", "0003_comment")]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        )
    ]
