# Generated by Django 2.2.3 on 2019-12-19 17:41

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0003_auto_20191218_1028")]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="hashtags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(blank=True),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
